

#define FIREBASE_ESP_CLIENT 1
#define ENABLE_NTP_TIME
#define USE_CONNECTION_KEEP_ALIVE_MODE
#define FIREBASE_ENABLE_RTDB
#define FIREBASE_DISABLE_NATIVE_ETHERNET
#define FIREBASE_GSM_MODEM_IS_AVAILABLE

#ifndef TINY_GSM_MODEM_SIM7080
#define TINY_GSM_MODEM_SIM7080
#endif
